# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  adapter: postgresql
  database: battlebox_production
  pool: 5
  host:localhost
  username:deployer
  password:secret
  

